version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TOKEN=${TOKEN}

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local