version: '3.9'
services:
  bot:
    image: batman-bot
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}
    environment:
      - TOKEN=${TOKEN}
    ports:
      - 3001:${PORT}
    env_file:
      - .env